name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
      with:
        clean: false
    - run: sudo docker-compose -f docker-compose.prod.yml --env-file .env up -d --build
